const messages={
 ja:{
  title:'クアッドリバーシ',titleAria:'クアッドリバーシ タイトル画面',boardAria:'10×10の盤面',newGame:'新しい対局',setupPhase:'対局設定',setupStatus:'人数と難易度を選んでください',setupDetail:'中央4×4を配置してから、4色で石を取り合います。',rules:'配置：中央の空きマスに順番に1個ずつ。16個で対局へ。\n対局：他の色を自分の色で挟んだ列を返します。置けない色は自動パス。全員置けなくなったら石数で決着。',setupTitle:'対局を始める',setupIntro:'人間の人数を選び、残りはCPUが担当します。各色の手番順は毎回ランダムです。',randomPlacement:'CPUの最初の4枚はランダムに配置します。',humans:'人間の人数',difficulty:'CPUの難易度',startGame:'対局開始',backTitle:'タイトルへ戻る',again:'もう一度遊ぶ',viewBoard:'盤面を見る',colors:['赤','青','黄','緑'],human:'人間',player:'プレイヤー{number}',empty:'空き',available:'配置可能',cell:'{row}行{col}列、{color}{hint}',placement:'配置フェーズ · {moves}/16',play:'対局フェーズ',turn:'{color} {kind}の手番',order:'順番：{order}。中央4×4の空きマスを選んでください。',legal:'光るマスに置けます（{count}か所）。',thinking:'CPUが考えています…',passed:'{count}色は置けずにパスしました。',ended:'対局終了',win:'{colors}の勝ち！',draw:'{colors}の引き分け',endDetail:'最多 {score}個。もう一度遊ぶには「新しい対局」を押してください。',resultWin:'最多 {score}個。おめでとうございます！',resultDraw:'最多 {score}個。同数トップです。',rank:'{rank}位',stones:'個',join:'・',bgmOn:'BGMをONにする',bgmOff:'BGMをOFFにする',descriptions:['','取れる石の数を重視','石数・角・次に置ける数を評価','次の色の応手も評価','応手を強めに評価','応手をさらに警戒し、終盤の石数も重視']
 },
 en:{
  title:'Quad Reversi',titleAria:'Quad Reversi title screen',boardAria:'10 by 10 board',newGame:'New game',setupPhase:'Game setup',setupStatus:'Choose players and difficulty',setupDetail:'Fill the central 4×4 area, then play four-color Reversi.',rules:'Placement: take turns placing a stone in an empty central cell. Play begins after all 16 cells are filled.\nPlay: bracket other colors with your own to flip them. Players with no legal move pass automatically. When nobody can move, the most stones wins.',setupTitle:'Set up a game',setupIntro:'Choose the number of human players. CPU players control the remaining colors. Turn order is randomized for each game.',randomPlacement:'Each CPU places its first four stones randomly.',humans:'Human players',difficulty:'CPU difficulty',startGame:'Play',backTitle:'Back to title',again:'Play again',viewBoard:'View board',colors:['Red','Blue','Yellow','Green'],human:'Human',player:'Player{number}',empty:'empty',available:'legal move',cell:'Row {row}, column {col}, {color}{hint}',placement:'Placement · {moves}/16',play:'Play phase',turn:'{color} {kind} to move',order:'Order: {order}. Choose an empty cell in the central 4×4 area.',legal:'Choose a highlighted cell ({count} legal moves).',thinking:'CPU is thinking…',passed:'{count} players passed because they had no legal move.',ended:'Game over',win:'{colors} wins!',draw:'{colors} tie!',endDetail:'Top score: {score} stones. Select “New game” to play again.',resultWin:'Top score: {score} stones. Congratulations!',resultDraw:'Top score: {score} stones. A shared victory!',rank:'#{rank}',stones:'stones',join:' & ',bgmOn:'Turn BGM on',bgmOff:'Turn BGM off',descriptions:['','Prioritizes the number of stones flipped','Evaluates stones, corners and mobility','Also evaluates the next opponent’s response','Places more weight on opponent responses','More cautious responses and stronger endgame scoring']
 }
};
let language='ja';try{if(localStorage.getItem('quad-reversi-language')==='en')language='en'}catch{}
export function getLanguage(){return language}
export function setLanguage(value){language=value==='en'?'en':'ja';try{localStorage.setItem('quad-reversi-language',language)}catch{}}
export function t(key,values={}){const value=messages[language][key];if(Array.isArray(value))return value;return value.replace(/\{(\w+)\}/g,(_,name)=>String(values[name]??''))}
